In this model we used Deep neural network regresser to predict led light life cycle and send a notification to electric centre before 2 to 4 days to install new led light in that area.
LED light life cycle prediction depends on many parameters like weather(high temperature, rainy days etc), voltage fluctuation, high load, how old the LED is , how many times the  light gets on off .
 
So for better accuracy, we use third party data for prediction.
So in this model we used supervised learning.

Time dataset taken from ------>>> Santa Monica GIS Data Portal 
link of the dataset is ------>>>>> https://gis-smgov.opendata.arcgis.com/datasets/a78ee2f14e2c437d9b66706ab0319339_0?geometry=-118.806%2C33.973%2C-118.153%2C34.073&where=DATE_SERV%20%3D%20%271999%27


**Import Needed Libraries**

In [0]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# **Load DataSet**
**Third Party Dataset**

In [0]:
dataset = pd.read_csv('Street_Lights.csv')

In [3]:
 dataset.drop(['PB_MANUFAC', 'PB_TYPE', 'PB_MOD_NUM', 'PB_WDTH_IN',
       'PB_LGTH_IN', 'PB_DEP_IN', 'REMARKS'], axis = 1)

,X,Y,OBJECTID,EH,POLE_ID,CIRCUIT_NU,LUMIN_TYPE,LAMP,MODEL,REFRACT_TY,...,KWH_USED,STRUCT_TYP,SYMBOL,PERIMETER,LIGHTS_,LIGHTS_ID,POLE_HT_FT,POLE_HT_IN,WIFI,AREA
0,6.415882e+06,1.822959e+06,2,LI1234,,318,,,,,...,0.0,G,152.0,0.0,2.0,1234.0,0.0,0.0,,0.0
1,6.410237e+06,1.833657e+06,3,LI1612,,78,,,,,...,0.0,G,152.0,0.0,3.0,1612.0,0.0,0.0,,0.0
2,6.417130e+06,1.825519e+06,4,LI2664,,242,,,,,...,0.0,G,152.0,0.0,4.0,2664.0,0.0,0.0,,0.0
3,6.419065e+06,1.825611e+06,5,LI4020,,308,,,,,...,0.0,G,152.0,0.0,5.0,4020.0,0.0,0.0,,0.0
4,6.411989e+06,1.837878e+06,6,LI4350,,13,,,,,...,0.0,G,152.0,0.0,6.0,4350.0,0.0,0.0,,0.0
5,6.418235e+06,1.831036e+06,7,LI5398,,131,,,,,...,0.0,G,152.0,0.0,7.0,5398.0,0.0,0.0,,0.0
6,6.412529e+06,1.838385e+06,8,LI5591,,8,,,,,...,0.0,G,152.0,0.0,8.0,5591.0,0.0,0.0,,0.0
7,6.412249e+06,1.838124e+06,9,LI5750,,11,,,,,...,0.0,G,152.0,0.0,9.0,5750.0,0.0,0.0,,0.0
8,6.413347e+06,1.838078e+06,10,LI5871,,6,,,,,...,0.0,G,152.0,0.0,10.0,5871.0,0.0,0.0,,0.0
9,6.413849e+06,1.838570e+06,11,LI5952,,4,,,,,...,0.0,G,152.0,0.0,11.0,5952.0,0.0,0.0,,0.0
10,6.417699e+06,1.836437e+06,12,LI7433,,22,,,,,...,0.0,G,152.0,0.0,12.0,7433.0,0.0,0.0,,0.0
11,6.413275e+06,1.824620e+06,14,LI8816,,313,,,,,...,0.0,G,152.0,0.0,14.0,8816.0,0.0,0.0,,0.0
12,6.409561e+06,1.829623e+06,15,10|4C51,8058,,POST TOP,H5,FP-199,ACORN GLOBE,...,0.0,SSL,155.0,0.0,15.0,207.0,0.0,0.0,,0.0
13,6.409713e+06,1.829768e+06,16,10|4C91,7770,,POST TOP,H5,FP-199,ACORN GLOBE,...,0.0,SSL,155.0,0.0,16.0,218.0,0.0,0.0,,0.0
14,6.409859e+06,1.829375e+06,17,10|4CB8,7980,,COBRA HEAD,H15,M250,FLAT GLASS,...,0.0,SSL,155.0,0.0,17.0,226.0,0.0,0.0,,0.0
15,6.409979e+06,1.829296e+06,18,10|4CBE,7937,,COBRA HEAD,H15,M250,FLAT GLASS,...,0.0,SSL,155.0,0.0,18.0,227.0,0.0,0.0,,0.0
16,6.410040e+06,1.829190e+06,19,10|4CC3,7978,,COBRA HEAD,H15,M250,FLAT GLASS,...,0.0,SSL,155.0,0.0,19.0,228.0,0.0,0.0,,0.0
17,6.409491e+06,1.829804e+06,20,10|4D42,7932,,COBRA HEAD,H10,M250,FLAT GLASS,...,0.0,SSL,155.0,0.0,20.0,253.0,0.0,0.0,,0.0
18,6.408995e+06,1.830293e+06,21,10|4DD9,7966,,POST TOP,H10,1990E,ACORN GLOBE,...,0.0,SSL,155.0,0.0,21.0,269.0,0.0,0.0,,0.0
19,6.409644e+06,1.829704e+06,22,10|547A,7863,,POST TOP,H5,FP-199,ACORN GLOBE,...,0.0,SSL,155.0,0.0,22.0,352.0,0.0,0.0,,0.0
20,6.411092e+06,1.828179e+06,23,11|5B82,7879,,COBRA HEAD,H20,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,23.0,391.0,0.0,0.0,,0.0
21,6.411053e+06,1.828114e+06,24,11|5BDA,7997,,,H36,,,...,0.0,SSL,155.0,0.0,24.0,410.0,0.0,0.0,,0.0
22,6.411489e+06,1.827737e+06,25,11|5C03,7930,,,UNK,,,...,0.0,SSL,155.0,0.0,25.0,419.0,0.0,0.0,,0.0
23,6.411374e+06,1.828464e+06,26,11|5C99,7541,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,26.0,445.0,0.0,0.0,,0.0
24,6.411946e+06,1.828428e+06,27,11|5D32,7198,,COBRA HEAD,H20,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,27.0,477.0,0.0,0.0,,0.0
25,6.412201e+06,1.829230e+06,28,11|5F2C,6755,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,28.0,563.0,0.0,0.0,,0.0
26,6.412294e+06,1.829150e+06,29,11|5F46,6746,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,29.0,568.0,0.0,0.0,,0.0
27,6.412292e+06,1.827199e+06,31,11|6729,7726,,HELMUT,H36,OV-35,DROP GLASS,...,0.0,SSL,155.0,0.0,31.0,754.0,0.0,0.0,,0.0
28,6.414727e+06,1.826430e+06,32,12|6FF3,6829,,,H15,,,...,0.0,SSL,155.0,0.0,32.0,761.0,0.0,0.0,,0.0
29,6.414618e+06,1.826339e+06,33,12|6FF7,6891,,,H15,,,...,0.0,SSL,155.0,0.0,33.0,762.0,0.0,0.0,,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21043,6.411956e+06,1.829014e+06,1972,LI18663,9387,135,,,,,...,0.0,SSLP,33.0,0.0,1972.0,18663.0,30.0,2.0,,0.0
21044,6.411956e+06,1.829014e+06,1973,LI18664,9387,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,1973.0,18664.0,0.0,0.0,,0.0
21045,6.411910e+06,1.828950e+06,1974,LI18665,,135,,,,,...,0.0,PB,149.0,0.0,1974.0,18665.0,0.0,0.0,,0.0
21046,6.411842e+06,1.828989e+06,1975,LI18666,,135,,,,,...,0.0,PB,149.0,0.0,1975.0,18666.0,0.0,0.0,,0.0
21047,6.411898e+06,1.829060e+06,1976,LI18667,,135,,,,,...,0.0,PB,149.0,0.0,1976.0,18667.0,0.0,0.0,,0.0
21048,6.411911e+06,1.828953e+06,1977,LI18668,9388,135,,,,,...,0.0,SSLP,33.0,0.0,1977.0,18668.0,30.0,0.0,,0.0
21049,6.411850e+06,1.828989e+06,1978,LI18670,9390,135,,,,,...,0.0,SSLP,33.0,0.0,1978.0,18670.0,30.0,0.0,,0.0
21050,6.411896e+06,1.829058e+06,1979,LI18671,9391,135,,,,,...,0.0,SSLP,33.0,0.0,1979.0,18671.0,30.0,2.0,,0.0
21051,6.411896e+06,1.829058e+06,1980,LI18676,9391,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,1980.0,18676.0,0.0,0.0,,0.0
21052,6.411850e+06,1.828989e+06,1981,LI18675,9390,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,1981.0,18675.0,0.0,0.0,,0.0
21053,6.411911e+06,1.828953e+06,1982,LI18673,9388,,COBRA HEAD,H25,M400,FLAT GLASS,...,0.0,SSL,155.0,0.0,1982.0,18673.0,0.0,0.0,,0.0
21054,6.421412e+06,1.826356e+06,1983,33|73CD,9398,,POST TOP,H7,PM17,LEXAN,...,0.0,SSL,155.0,0.0,1983.0,5443.0,0.0,0.0,,0.0
21055,6.419840e+06,1.824216e+06,1984,20|C2C,5458,,COBRA HEAD,H10,M-250A2,CUTOFF,...,0.0,SSL,155.0,0.0,1984.0,2794.0,0.0,0.0,,0.0
21056,6.419041e+06,1.825750e+06,1985,26|7C0F,5120,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1985.0,4001.0,0.0,0.0,,0.0
21057,6.419135e+06,1.825660e+06,1986,26|7C16,5117,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1986.0,4003.0,0.0,0.0,,0.0
21058,6.419236e+06,1.825680e+06,1987,26|7C1F,5088,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1987.0,4005.0,0.0,0.0,,0.0
21059,6.419295e+06,1.825769e+06,1988,26|7C22,5019,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1988.0,4006.0,0.0,0.0,,0.0
21060,6.419421e+06,1.825807e+06,1989,26|7C2B,4939,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1989.0,4008.0,0.0,0.0,,0.0
21061,6.419495e+06,1.825907e+06,1990,26|7C2E,4849,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1990.0,4009.0,0.0,0.0,,0.0
21062,6.419602e+06,1.825933e+06,1991,26|7C36,4815,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1991.0,4011.0,0.0,0.0,,0.0
21063,6.419698e+06,1.825836e+06,1992,26|7C3B,4814,,PENDANT,H7,NaN,ACORN,...,0.0,SSL,155.0,0.0,1992.0,4012.0,0.0,0.0,,0.0
21064,6.419495e+06,1.825907e+06,1993,LI13183,4849,308,,,,,...,0.0,SSLP,33.0,0.0,1993.0,13183.0,17.0,4.0,,0.0
21065,6.419041e+06,1.825750e+06,1994,LI13185,5120,308,,,,,...,0.0,SSLP,33.0,0.0,1994.0,13185.0,17.0,4.0,,0.0
21066,6.419135e+06,1.825660e+06,1995,LI13188,5117,308,,,,,...,0.0,SSLP,33.0,0.0,1995.0,13188.0,17.0,4.0,,0.0
21067,6.419236e+06,1.825680e+06,1996,LI13190,5088,308,,,,,...,0.0,SSLP,33.0,0.0,1996.0,13190.0,17.0,4.0,,0.0
21068,6.419295e+06,1.825769e+06,1997,LI13191,5019,308,,,,,...,0.0,SSLP,33.0,0.0,1997.0,13191.0,17.0,4.0,,0.0
21069,6.419421e+06,1.825807e+06,1998,LI13193,4939,308,,,,,...,0.0,SSLP,33.0,0.0,1998.0,13193.0,17.0,4.0,,0.0
21070,6.419602e+06,1.825933e+06,1999,LI13194,4815,308,,,,,...,0.0,SSLP,33.0,0.0,1999.0,13194.0,17.0,4.0,,0.0
21071,6.419698e+06,1.825836e+06,2000,LI13196,4814,308,,,,,...,0.0,SSLP,33.0,0.0,2000.0,13196.0,17.0,4.0,,0.0
21072,6.419716e+06,1.825892e+06,2001,LI13198,,308,,,,,...,0.0,PCS,153.0,0.0,2001.0,13198.0,0.0,0.0,,0.0

In [0]:
Data = dataset.drop(['X', 'Y', 'OBJECTID', 'EH', 'POLE_ID', 'CIRCUIT_NU', 'LUMIN_TYPE',
       'LAMP', 'MODEL', 'REFRACT_TY', 'REFRACT_MT', 'BALLAST_MF', 'BALLAST_MO',
       'BALLAST_TY', 'LED_LIGHT', 'LED_MANUFA', 'DRIVER_MOD', 'DRIVER_TYP',
       'DRIVER_MF','DATE_INSP', 'FIXTURE_NU',
       'METERED', 'MAP_REFERE', 'POLE_TYPE', 'POLE_COND', 'POLE_BASE_',
       'POLE_USAGE', 'ARM_LENGTH', 'ARM_TYPE', 'POLE_MFG', 'FINISH',
       'MATERIAL', 'BOLT_PATTE', 'POST_TOP', 'NUM_FIXTUR', 'OWNERSHIP',
       'ADDRESS', 'ADDDESC', 'STREET', 'NEAREST_IN', 'NUM_LIGHTS', 'KEYCODE',
       'CABINET_CO', 'CABINET_NU', 'MODEL_NUM', 'SERIES', 'MULTIPLE',
       'METER_NUM', 'CUST_NUM', 'SERV_NUM', 'KWH_USED', 'STRUCT_TYP', 'SYMBOL',
       'PERIMETER', 'LIGHTS_', 'LIGHTS_ID', 'POLE_HT_FT', 'POLE_HT_IN', 'WIFI',
       'AREA', 'PB_MANUFAC', 'PB_TYPE', 'PB_MOD_NUM', 'PB_WDTH_IN',
       'PB_LGTH_IN', 'PB_DEP_IN', 'REMARKS'], axis = 1)

**And Load Given DataSet by EESL**

In [0]:
d = pd.read_excel('Load_Survey_Data.xlsx')

# Refine DataSet

Refine thrid party data only 28 example used

In [0]:
Data = Data[Data.DATE_INSTA  != ' ']

In [0]:
Data = Data[Data.DATE_SERV  != ' ']

In [0]:
Data = Data.dropna()

In [0]:
Data = Data.drop([17916])

In [0]:
Data = Data.reset_index()

In [0]:
Data = Data.drop(['index'], axis =1)

In [12]:
Data

   DATE_INSTA DATE_SERV
0        1964      1999
1        1964      1999
2        1964      1999
3        1964      1999
4        1964      1999
5        1964      1999
6        1964      1999
7        1964      1999
8        1964      1999
9        1964      1999
10       1964      1999
11       1964      1999
12       1964      1999
13       1964      1999
14       1964      1999
15       1964      1999
16       1964      1999
17       1964      1999
18       1964      1999
19       1964      1999
20       1964      1999
21       1964      1999
22       1964      1999
23       1964      1999
24       1964      1999
25       1964      1999
26       1964      1999
27       1964      1999

In [13]:
Data.dtypes

DATE_INSTA    object
DATE_SERV     object
dtype: object

In [0]:
Data = Data.apply(pd.to_numeric, errors='coerce')

In [0]:
Data = Data.iloc[:,:]+ 0.0

In [16]:
d.columns

Index(['CCMS ID', 'Timestamp', 'KWh', 'KVAh', 'Vr', 'Vy', 'Vb', 'Ir', 'Iy',
       'Ib', 'Freq (Hz)', 'PF Total', 'Total Load'],
      dtype='object')

In [0]:
d = d.drop(['CCMS ID', 'Timestamp', 'KWh', 'KVAh', 'Freq (Hz)',
       'PF Total', 'Total Load'], axis = 1)

In [18]:
type(Data)

pandas.core.frame.DataFrame

In [0]:
d = d.iloc[:28]

In [20]:
len(Data)

28

In [21]:
type(d)

pandas.core.frame.DataFrame

In [22]:
len(d)

28

In [23]:
Data.dtypes

DATE_INSTA    float64
DATE_SERV     float64
dtype: object

**ConCatinate given data and thrid party data **

In [0]:
Data_set = pd.concat([Data, d],axis = 1)

In [25]:
Data_set

    DATE_INSTA  DATE_SERV      Vr      Vy      Vb     Ir    Iy    Ib
0       1964.0     1999.0  233.23  234.30  235.21  10.31  5.41  5.79
1       1964.0     1999.0  236.64  238.00  238.73  10.53  5.40  5.78
2       1964.0     1999.0  237.01  238.69  239.36  10.54  5.40  5.79
3       1964.0     1999.0  237.29  238.79  239.56   9.71  5.42  5.79
4       1964.0     1999.0  244.08  245.06  245.75   0.52  0.26  0.26
5       1964.0     1999.0  241.00  241.85  242.38   0.00  0.00  0.00
6       1964.0     1999.0  239.73  240.39  240.82   0.00  0.00  0.00
7       1964.0     1999.0  238.14  238.96  239.35   0.00  0.00  0.00
8       1964.0     1999.0  241.32  241.94  242.50   0.00  0.00  0.00
9       1964.0     1999.0  244.48  244.98  245.67   0.00  0.00  0.00
10      1964.0     1999.0  243.99  244.54  245.26   0.00  0.00  0.00
11      1964.0     1999.0  243.82  244.59  245.16   0.00  0.00  0.00
12      1964.0     1999.0  244.05  244.75  245.51   0.00  0.00  0.00
13      1964.0     1999.0  246.35  246.96  247.61   0.00  0.00  0.00
14      1964.0     1999.0  250.94  251.58  252.25   0.00  0.00  0.00
15      1964.0     1999.0  251.32  252.00  252.41   0.00  0.00  0.00
16      1964.0     1999.0  249.03  249.43  250.21   0.00  0.00  0.00
17      1964.0     1999.0  247.29  248.34  249.27   6.96  3.93  4.21
18      1964.0     1999.0  245.06  246.21  246.95  10.37  5.23  5.61
19      1964.0     1999.0  243.35  244.27  245.12  10.40  5.26  5.63
20      1964.0     1999.0  240.55  241.47  242.28  10.51  5.36  5.72
21      1964.0     1999.0  235.94  236.88  237.74  10.74  5.50  5.87
22      1964.0     1999.0  234.46  235.98  236.67  10.86  5.56  5.94
23      1964.0     1999.0  230.43  231.22  231.92  11.04  5.68  6.55
24      1964.0     1999.0  231.68  232.71  233.48  10.74  5.52  6.38
25      1964.0     1999.0  234.96  236.24  236.85  10.55  5.42  6.26
26      1964.0     1999.0  236.29  237.72  237.91  10.25  5.43  6.29
27      1964.0     1999.0  238.18  239.57  239.84   9.69  5.41  6.26

In [0]:
x_data = Data_set

In [27]:
x_data

    DATE_INSTA  DATE_SERV      Vr      Vy      Vb     Ir    Iy    Ib
0       1964.0     1999.0  233.23  234.30  235.21  10.31  5.41  5.79
1       1964.0     1999.0  236.64  238.00  238.73  10.53  5.40  5.78
2       1964.0     1999.0  237.01  238.69  239.36  10.54  5.40  5.79
3       1964.0     1999.0  237.29  238.79  239.56   9.71  5.42  5.79
4       1964.0     1999.0  244.08  245.06  245.75   0.52  0.26  0.26
5       1964.0     1999.0  241.00  241.85  242.38   0.00  0.00  0.00
6       1964.0     1999.0  239.73  240.39  240.82   0.00  0.00  0.00
7       1964.0     1999.0  238.14  238.96  239.35   0.00  0.00  0.00
8       1964.0     1999.0  241.32  241.94  242.50   0.00  0.00  0.00
9       1964.0     1999.0  244.48  244.98  245.67   0.00  0.00  0.00
10      1964.0     1999.0  243.99  244.54  245.26   0.00  0.00  0.00
11      1964.0     1999.0  243.82  244.59  245.16   0.00  0.00  0.00
12      1964.0     1999.0  244.05  244.75  245.51   0.00  0.00  0.00
13      1964.0     1999.0  246.35  246.96  247.61   0.00  0.00  0.00
14      1964.0     1999.0  250.94  251.58  252.25   0.00  0.00  0.00
15      1964.0     1999.0  251.32  252.00  252.41   0.00  0.00  0.00
16      1964.0     1999.0  249.03  249.43  250.21   0.00  0.00  0.00
17      1964.0     1999.0  247.29  248.34  249.27   6.96  3.93  4.21
18      1964.0     1999.0  245.06  246.21  246.95  10.37  5.23  5.61
19      1964.0     1999.0  243.35  244.27  245.12  10.40  5.26  5.63
20      1964.0     1999.0  240.55  241.47  242.28  10.51  5.36  5.72
21      1964.0     1999.0  235.94  236.88  237.74  10.74  5.50  5.87
22      1964.0     1999.0  234.46  235.98  236.67  10.86  5.56  5.94
23      1964.0     1999.0  230.43  231.22  231.92  11.04  5.68  6.55
24      1964.0     1999.0  231.68  232.71  233.48  10.74  5.52  6.38
25      1964.0     1999.0  234.96  236.24  236.85  10.55  5.42  6.26
26      1964.0     1999.0  236.29  237.72  237.91  10.25  5.43  6.29
27      1964.0     1999.0  238.18  239.57  239.84   9.69  5.41  6.26

In [0]:
x_data = x_data.drop(['DATE_SERV'], axis = 1)

In [29]:
x_data.columns

Index(['DATE_INSTA', 'Vr', 'Vy', 'Vb', 'Ir', 'Iy', 'Ib'], dtype='object')

In [0]:
DATE_INSTA = tf.feature_column.numeric_column('DATE_INSTA')
vr = tf.feature_column.numeric_column('Vr')
Vy = tf.feature_column.numeric_column('Vy')
Vb = tf.feature_column.numeric_column('Vb')
Ir = tf.feature_column.numeric_column('Ir')
Iy = tf.feature_column.numeric_column('Iy')
ib = tf.feature_column.numeric_column('Ib')

In [0]:
feat_cols = [DATE_INSTA, vr, Vy, Vb, Ir, Iy, ib]

In [0]:
rat = Data_set['DATE_SERV']

In [33]:
x_data.head()

   DATE_INSTA      Vr      Vy      Vb     Ir    Iy    Ib
0      1964.0  233.23  234.30  235.21  10.31  5.41  5.79
1      1964.0  236.64  238.00  238.73  10.53  5.40  5.78
2      1964.0  237.01  238.69  239.36  10.54  5.40  5.79
3      1964.0  237.29  238.79  239.56   9.71  5.42  5.79
4      1964.0  244.08  245.06  245.75   0.52  0.26  0.26

In [34]:
x_data.dtypes

DATE_INSTA    float64
Vr            float64
Vy            float64
Vb            float64
Ir            float64
Iy            float64
Ib            float64
dtype: object

In [35]:
type(rat)

pandas.core.series.Series

In [36]:
type(x_data)

pandas.core.frame.DataFrame

In [37]:
rat.dtypes

dtype('float64')

# Now Start

**Split Dataset into Train and Test**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(x_data, rat, test_size = 0.3, random_state = 101)

In [0]:
input_func = tf.estimator.inputs.pandas_input_fn(x = X_train, y = y_train, batch_size = 32, num_epochs = 1500, shuffle = True)

**In This we use DNNRegressor**

------>>>>
In this we use 6 hidden layer in NN

In [41]:
dnn_model = tf.estimator.DNNRegressor(hidden_units = [20, 30, 16, 6, 10, 15], feature_columns = feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpnqx0gr6l
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpnqx0gr6l', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fddb2b72710>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [42]:
dnn_model.train(input_fn = input_func, steps = 25000)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/feature_column_v2.py:2703: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py:809: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpnqx0gr6l/model.ckpt.
INFO:tensorflow:loss = 119789620.0, step = 0
INFO:tensorflow:global_step/sec: 196.458
INFO:tensorflow:loss = 125.933266, step = 100 (0.512 sec)
INFO:tensorflow:global_step/sec: 228.217
INFO:tensorflow:loss = 148.7787, step = 200 (0.438 sec)
INFO:tensorflow:global_step/sec: 223.954
INFO:tensorflow:loss = 142.97583, step = 300 (0.446 sec)
INFO:tensorflow:global_step/sec: 228.127
INFO:tensorflow:loss = 75.15891, step = 400 (0.442 sec)
INFO:tensorflow:global_step/sec: 228.974
INFO:tensorflow:loss = 97.68021, step = 500 (0.437 sec)
INFO:tensorflow:global_step/sec: 236.473
INFO:tensorflow:loss = 98.976974, step = 600 (0.422 sec)
INFO:tensorflow:global_step/sec: 238.733
INFO:tensorflow:loss = 121.32773, step = 700 (0.419 sec)
INFO:tensorflow:global_step/sec: 218.125
INFO:tensorflow:loss = 64.40215, step = 800 (0.457 sec)
INFO:tensorflow:Saving checkpoints for 891 into /tmp/tmpnqx0gr6l/model.ckpt.
INFO:tensorflow:Loss for final step: 73.55493.

In [0]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(
      x=X_test,
      batch_size=10,
      num_epochs=1,
      shuffle=False)

In [0]:
pred_gen = dnn_model.predict(predict_input_func)

In [45]:
predictions = list(pred_gen)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/tmpnqx0gr6l/model.ckpt-891
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

In [0]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['predictions'])

We predicate output of this data

In [47]:
final_preds

[array([2000.9056], dtype=float32),
 array([1995.4689], dtype=float32),
 array([1996.663], dtype=float32),
 array([2001.1473], dtype=float32),
 array([1997.5117], dtype=float32),
 array([1996.8125], dtype=float32),
 array([1997.1628], dtype=float32),
 array([1996.5162], dtype=float32),
 array([1999.0402], dtype=float32)]

In [0]:
from sklearn.metrics import mean_squared_error

Error is only 2.36

In [49]:
mean_squared_error(y_test,final_preds)**0.5

2.1786620858771997